import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Instrument_Serif,
  Rethink_Sans,
  Space_Mono,
  VT323,
} from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/navigation/header';
import Footer from '@/components/navigation/footer';
import SmoothScroll from '@/components/smooth-scroll';
import ContactForm from '@/components/home/contactForm';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const rethinkSans = Rethink_Sans({
  variable: '--font-rethink-sans',
  subsets: ['latin'],
  display: 'swap',
});

const instrumentSerif = Instrument_Serif({
  variable: '--font-instrument-serif',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
});

const vt = VT323({
  variable: '--font-vt',
  subsets: ['latin'],
  weight: ['400'],
});

const spaceMono = Space_Mono({
  variable: '--font-space-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rethinkSans.variable} ${instrumentSerif.variable} ${vt.variable} ${spaceMono.variable} font-[family-name:var(--font-rethink-sans)] antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <SmoothScroll>
            <Header />

            {children}
            <ContactForm />

            <Footer />
          </SmoothScroll>
        </ThemeProvider>
      </body>
    </html>
  );
}
